### ISSUE TITLE
Problem with analysis of resifinder and virulence finder data

### ISSUE THREAD

**Issue by solveigmo** [hkaspersen/ARIBA_analysis#1]
Tried the Ariba_analysis script on output from resfinder and virulence finder databases, but got the following error message;
 
Error: `by` can't contain join column `ref_name` which is missing from LHS
In addition: Warning message:
Unknown or uninitialised column: 'ref_name'.
Execution halted

**Comment by hkaspersen** [comment]
Will be fixed in future update to include virulence analysis
