### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by solveigmo** [hkaspersen/ARIBA_analysis#2]
Error in mutate_impl(.data, dots) :
  Evaluation error: object 'Absent' not found.
Calls: calc_stats ... <Anonymous> -> mutate -> mutate.tbl_df -> mutate_impl
Execution halted

**Comment by hkaspersen** [comment]
Fixed by adding the following code to the "calc_stats" function:

```
mutate(Absent = if ("Absent" %in% names(.)) {
      return(Absent)
    } else {
      return(0) # adds Absent column with all 0 if all isolates have genes
    })
```
When all isolates analysed were positive for all genes, "Absent" was not being spread into a separate column, thus throwing an error.
