### ISSUE TITLE
Error with parC

### ISSUE THREAD

**Issue by solveigmo** [hkaspersen/ARIBA_analysis#3]
Location;
/work/projects/nn9305k/ecoli/analysis/NoResist/solveig_test/Bifrostresults/SPEC_GEN

Code;
Rscript /work/projects/nn9305k/vi_src/ARIBA_analysis/ariba_analysis.R MEAT4/Megares/Results/amr_results/ MEAT4/ResVirfinder/Results/amr_results/ MEAT4/AribaAnalysis/ acquired_genes intrinsic_genes FALSE

Error-message;
Error: Unknown column `parC`
Execution halted

**Comment by hkaspersen** [comment]
Fixed by changing the calc_no_of_mut function, as a filtering step was removing empty columns when it shouldn't.
